FROM alpine:3.19

RUN sed -i 's/dl-cdn.alpinelinux.org/mirror.yandex.ru/g' /etc/apk/repositories && \
    apk add --no-cache \
        postgresql-client \
        wget \
        ca-certificates \
        bash

WORKDIR /app

ENTRYPOINT ["/bin/sh"]
CMD []
