-- Migration 059: Create default admin user if not exists
-- This ensures there's always an admin user after deployment
-- Credentials: admin@tutoring.com / admin123

-- Insert admin user only if he doesn't exist
-- Password: admin123 (BCrypt hash generated by Go bcrypt.DefaultCost)
INSERT INTO users (id, email, password_hash, first_name, last_name, full_name, role, payment_enabled, created_at, updated_at)
SELECT
    '00000000-0000-0000-0000-000000000001',
    'admin@tutoring.com',
    '$2a$10$69LiLa1TOJJeVNC1TwFIg.4Ma1eFjlG38FtZ7/AjkSw71X0qK46Qi',
    'Admin',
    '',
    'Admin',
    'admin',
    true,
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE email = 'admin@tutoring.com'
);

-- Initialize credits for admin user (only if no credits exist)
INSERT INTO credit_transactions (user_id, amount, balance_after, description)
SELECT
    u.id,
    1000,
    1000,
    'Initial admin credits'
FROM users u
WHERE u.email = 'admin@tutoring.com'
  AND NOT EXISTS (
    SELECT 1 FROM credit_transactions ct
    WHERE ct.user_id = u.id
  );
